### ISSUE TITLE
Soundness issues

### ISSUE THREAD

**Issue by ggriffiniii** [redsift/redbpf#20] opened 2019-12-20 17:17 UTC
I was reading the post at https://blog.redsift.com/labs/writing-bpf-code-in-rust/ and started playing around with it. While debugging I glanced at the source code for Data::read here:

https://github.com/redsift/redbpf/blob/master/redbpf-probes/src/xdp.rs#L236
```rust
    pub fn read<T>(&self) -> Option<T> {
        unsafe {
            let len = mem::size_of::<T>();
            if self.base.add(len) as *const u8 > (*self.ctx).data_end as *const u8 {
                return None;
            }
            Some((self.base as *const T).read_unaligned())
        }
    }
```

This function is not sound for all values of T and should at least be marked unsafe. Right beneath that is the MapData type which appears to be equally unsound and at the very least should have the payload method marked unsafe.

These are just the first pieces of code I glanced at when trying to figure out what the http trace example in the blog post is doing, it is far from an exhaustive scan of the redbpf code base.

Would you welcome changes that mark those API's unsafe?

**Comment by alessandrod** [comment] 2019-12-23 07:47
> I was reading the post at https://blog.redsift.com/labs/writing-bpf-code-in-rust/ and started playing around with it.

Thanks for checking it out and taking the time to go through the code :)

> https://github.com/redsift/redbpf/blob/master/redbpf-probes/src/xdp.rs#L236
> 
> ```rust
>     pub fn read<T>(&self) -> Option<T> {
> ```
> 
> This function is not sound for all values of T and should at least be marked unsafe.

First let me start by saying that pretty much all the APIs are unstable and are likely going to change. So far we've put more focus on the overall infrastructure to get things running than on the API details. The existing APIs cover what we've needed so far to implement use cases in ingraind. We're going to put much more focus on the APIs going forward, as the basics are now in place.

That said, `read()` is actually supposed to be
```rust
     pub fn read<const N: usize>(&self) -> Option<[u8; N]> {
```

At which point it can be made safe and sound. Const generics are slowly getting there (they're now used internally by the rust compiler), so hopefully we'll be able to do that soon.

> Right beneath that is the MapData type which appears to be equally unsound and at the very least should have the payload method marked unsafe.

So `MapData` is a type that is used to abstract the way the kernel attaches XDP data to a map entry. Then on user space, `MapData::payload()` can be used to retrieve the XDP data.

What makes `MapData` currently unsound is that today you can do:
```rust
let data = MapData::with_payload((), x, y);
let p = data.payload();
```

That is not the intended use tho: `MapData` is only meant to be created by kernel code, inserted in a map, and then `MapData::payload` is only meant to be called by user space after having been retrieved from the map. If used as intended, `payload()` is guaranteed to be safe, because when inserting a map entry the kernel internally checks that the requested payload size is valid. 

We currently don't have a way to mark some types/methods as kernel space only and user space only. `MapData` is the first case in which we need this, so we'll have to come up with something. A proposal of a solution would be very welcome.  

> These are just the first pieces of code I glanced at when trying to figure out what the http trace example in the blog post is doing, it is far from an exhaustive scan of the redbpf code base.
> 
> Would you welcome changes that mark those API's unsafe?

In this specific case I think we can do better and end up with a safe API. Generally speaking one goal is obviously to have no unsound code. Soundness bugs must be fixed. Another equally important goal is to create idiomatic APIs.

BPF is kind of a strange target. The majority of BPF code deals with pointers, which is unsafe by definition. BPF programs are not regular rust programs tho. The verifier runs static analysis on a program before loading it so for example pointer math, which is unsafe by definition in Rust, is actually safe in the context of BPF.  Therefore whenever possible, we want to actually reduce the need for unsafe otherwise we'll end up quickly having to put everything in a huge unsafe { } block (which is actually where we started from before we started abstracting away things :))

**Comment by ggriffiniii** [comment] 2019-12-23 16:56
> > I was reading the post at https://blog.redsift.com/labs/writing-bpf-code-in-rust/ and started playing around with it.
> 
> Thanks for checking it out and taking the time to go through the code :)

Thanks for responding. I think this is great work that you're doing. I'm just now diving into the world of bpf and I was happy to see that somebody was working on a rust interface. Please know that I hope none of my comments come across as disparaging. I'm coming from the perspective of a new user to the project and I'm hopeful that I can help give a sense of that perspective.

> 
> > https://github.com/redsift/redbpf/blob/master/redbpf-probes/src/xdp.rs#L236
> > ```rust
> >     pub fn read<T>(&self) -> Option<T> {
> > ```
> > 
> > 
> > This function is not sound for all values of T and should at least be marked unsafe.
> 
> First let me start by saying that pretty much all the APIs are unstable and are likely going to change. So far we've put more focus on the overall infrastructure to get things running than on the API details. The existing APIs cover what we've needed so far to implement use cases in ingraind. We're going to put much more focus on the APIs going forward, as the basics are now in place.
> 
> That said, `read()` is actually supposed to be
> 
> ```rust
>      pub fn read<const N: usize>(&self) -> Option<[u8; N]> {
> ```
> 
> At which point it can be made safe and sound. Const generics are slowly getting there (they're now used internally by the rust compiler), so hopefully we'll be able to do that soon.

Glad to hear that's the planned interface. That said, I cannot stress enough that I feel like the current interface is actively harmful. Not only to users, but also to yourself as you're implementing. You're violating rust's most fundamental guarantee and that would make any rust user question the work you're doing.

I would suggest either putting the const-generics interface behind a feature flag that makes it only work on nightly, or marking the current function unsafe with a comment that it's only safe when reading into a byte array.

As an aside, I think a more flexible version of read than the proposed:
 ```rust
      pub fn read<const N: usize>(&self) -> Option<[u8; N]> {
 ```
would be something that uses the [zerocopy](https://docs.rs/zerocopy) traits to reinterpret bytes into user defined structures that are safe to be treated as a series of arbitrary bits. I haven't used that crate previously, but it *seems* well suited to this task.

> > Right beneath that is the MapData type which appears to be equally unsound and at the very least should have the payload method marked unsafe.
> 
> So `MapData` is a type that is used to abstract the way the kernel attaches XDP data to a map entry. Then on user space, `MapData::payload()` can be used to retrieve the XDP data.
> 
> What makes `MapData` currently unsound is that today you can do:
> 
> ```rust
> let data = MapData::with_payload((), x, y);
> let p = data.payload();
> ```
> 
> That is not the intended use tho: `MapData` is only meant to be created by kernel code, inserted in a map, and then `MapData::payload` is only meant to be called by user space after having been retrieved from the map. If used as intended, `payload()` is guaranteed to be safe, because when inserting a map entry the kernel internally checks that the requested payload size is valid.

This paragraph describing when it's acceptable to call certain methods, is exactly what should be commented above the methods, and the methods should be marked unsafe. Really, anything else is again just violating the most fundamental principles of rust. It's perfectly acceptable to not have a safe interface for everything, but it's completely unacceptable to advertise a safe interface that is not.

I can understand that the API's are still a work in progress and as a user coming into the codebase I wouldn't have blinked an eye if the interfaces had some rough edges and the majority of them were unsafe. That would be completely understandable especially for such a low-level library, but when I saw interfaces advertised as safe that were not upholding the necessary guarantees it made me question whether I could ever trust this codebase for any work I plan to do. Again, I say this to provide an outsiders perspective, not to disparage any of your work.

> We currently don't have a way to mark some types/methods as kernel space only and user space only. `MapData` is the first case in which we need this, so we'll have to come up with something. A proposal of a solution would be very welcome.

This may be a naive suggestion, but the simplest thing that comes to my mind is that you don't need the MapData type used within kernel space to be the same MapData type used in user space. I could imagine having two separate modules, one for use by the bpf program in kernel space, and another for use by user space programs reading the bpf output. The two modules could each have their own MapData type. The kernel space one would only provide the `with_payload` method, and the user space one would only provide the `payload` method.

> 
> > These are just the first pieces of code I glanced at when trying to figure out what the http trace example in the blog post is doing, it is far from an exhaustive scan of the redbpf code base.
> > Would you welcome changes that mark those API's unsafe?
> 
> In this specific case I think we can do better and end up with a safe API. Generally speaking one goal is obviously to have no unsound code. Soundness bugs must be fixed. Another equally important goal is to create idiomatic APIs.

This may be a nitpick but those should not be treated as *equally* important. Everyone strives to make idiomatic API's and that is very important, but you *should never* knowingly write a safe api with soundness holes. Surely bugs happen and there will be soundness holes in api's that you intend to be safe, but you should never knowingly mark a function as safe when you know there are places where it is not. That is exactly what unsafe is for, to alert people that *they* are responsible for upholding some invariant that the compiler can not check.

> 
> BPF is kind of a strange target. The majority of BPF code deals with pointers, which is unsafe by definition. BPF programs are not regular rust programs tho. The verifier runs static analysis on a program before loading it so for example pointer math, which is unsafe by definition in Rust, is actually safe in the context of BPF. Therefore whenever possible, we want to actually reduce the need for unsafe otherwise we'll end up quickly having to put everything in a huge unsafe { } block (which is actually where we started from before we started abstracting away things :))

Yeah, the fact that BPF is going to perform it's own safety verification is nice and should provide users with a lot of confidence that they aren't going to wreak havoc on the system with some malformed code. I still think there is a lot of room to make some safe wrappers in rust so that the compiler give me an error rather than getting an error when I attempt to load the module.

**Comment by rsdy** [comment] 2019-12-24 00:31
@ggriffiniii I think you're raising an important issue here, but I think it's also important to consider the context in which these functions can be used in order to determine their soundness. Right now, as @alessandrod wrote, the exposed functions are only unsound if they are being used in userspace, incorrectly.

> That said, I cannot stress enough that I feel like the current interface is actively harmful. 
I disagree with this. In my reading `read` is not unsound, although it probably would be in userspace. The `if` check is mandatory according to the BPF verifier, and therefore `read` guarantees correct memory access.

I would like to steer this debate towards finding a way to unambiguously mark interfaces that can be used in userspace and kernel space. This will help us leverage Rust's power more during the compilation phase, and make more clear whether a type or function can be unsound. This will also help us analyse code for soundness in context.

**Comment by ggriffiniii** [comment] 2019-12-26 17:15
> @ggriffiniii I think you're raising an important issue here, but I think it's also important to consider the context in which these functions can be used in order to determine their soundness. Right now, as @alessandrod wrote, the exposed functions are only unsound if they are being used in userspace, incorrectly.

There seems to be a disconnect on what `unsafe` means because what you described there is exactly why these functions should be marked as `unsafe`. To quote the rust [nomicon](https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html)

**No matter what, Safe Rust can't cause Undefined Behavior.**

There can't be any conditional qualifiers to safe code. If you have to say "_only unsound if_" then the function should be marked `unsafe`. There are no qualifiers that make this okay. Even baremetal operating systems written almost entirely in rust can only mark a function as safe it it's *impossible* for it to produce undefined behavior. Also note that memory safety is not the only constraint that safe code needs to abide by, there are plenty of invariants that need to be upheld in rust that are not strictly necessary for memory safety.

I also want to point out that you shouldn't be hesitant to use unsafe. You're writing low-level code that needs to interact with the OS, everyone is going to understand a certain amount of unsafe is necessary here. It would be great to wrap these interfaces in a way that provides a safe mechanism to use the functionality, but that takes a lot of time and thought to do properly. Until that happens you aren't doing *anybody* any favors by marking a function as safe while it's not. You lose a lot of trust from people looking to use the library by doing that. This last point is hard to quantify, but is critically important. The only reason I thought to look at the implementation of read was because the function signature was so fishy I couldn't believe it, but now that I have I feel like I would need to read through the whole code base before I could use any piece of it. Safe code is self documenting, unsafe code informs the user that there are invariants they are responsible for upholding.

> > That said, I cannot stress enough that I feel like the current interface is actively harmful.
> 
> I disagree with this. In my reading `read` is not unsound, although it probably would be in userspace. The `if` check is mandatory according to the BPF verifier, and therefore `read` guarantees correct memory access.

Surely the current `read` is not safe and never could be even in kernel space. Not all types can be interpreted as an arbitrary byte stream. Attempting to perform a read for a core::num::NonZeroU8 would be a simple example. The bpf verifier would allow that anytime the buffer contains a single byte, but obviously that byte could be zero thus violating the necessary invariants.

I feel like the difference between kernel space and user space is not as important for this topic as you seem to imply. I know the BPF verifier is going to ensure there aren't any invalid memory access, but the safe/unsafe boundary still needs to be maintained. Even if you didn't want to uphold rust's properties in kernel space, it would be better to have all the interfaces marked as unsafe and enclose the entire bpf code in a giant unsafe block than to do what read is doing.

> I would like to steer this debate towards finding a way to unambiguously mark interfaces that can be used in userspace and kernel space. This will help us leverage Rust's power more during the compilation phase, and make more clear whether a type or function can be unsound. This will also help us analyse code for soundness in context.

I provided ideas for methods to make the interfaces sound in the previous comment (use the zerocopy traits, and split the types into a kernel space type and a user space type with appropriate methods for each), but making sound interfaces is hard and takes time. I greatly appreciate the work you're doing, but the first step should be to follow the rules of rust and mark unsafe functions unsafe. Then you can take your time to figure out the best way to present a safe interface.

**Comment by nickray** [comment] 2020-01-08 15:53
Maybe consider `generic-array` since const-generics seems not quite around the corner?

**Comment by withoutboats** [comment] 2020-01-08 22:24
If `T` is always supposed to be a byte array, you could make this safe on stable today by bounding it by a new trait only implemented for byte arrays. Obviously this is a lot of impls if the maximum size of array allowed is very high, but if not it could be a safe solution that's less heavyweight than generic-array.

**Comment by rsdy** [comment] 2020-01-08 22:46
@withoutboats Actually that's something that could work. The usecase here is primarily reading Ethernet/IP/TCP/UDP data, so I think we could get away with 9000 impls, as 9000 bytes is the standard maximum size for jumbo frames.

**Comment by HeroicKatora** [comment] 2020-01-09 19:43
The computation testing if the type exceeds the length of the available data is unfortunately unsound in itself already. The requirements for `pointer::add` state:

* Both the starting and resulting pointer must be either in bounds or one byte past the end of the same allocated object. Note that in Rust, every (stack-allocated) variable is considered a separate allocated object.
* The offset being in bounds cannot rely on "wrapping around" the address space. That is, the infinite-precision sum must fit in a usize.

Calling `pointer::add` is the equivalent of asserting to the compiler that the result will be within bounds of the allocation. However, both of these can not be guaranteed until *after* the length has been validated as the argument `mem::size_of::<T>()` is provided by the caller. Instead, you should compare the size of the argument to the separately computed actual length.

**Comment by rsdy** [comment] 2020-02-27 11:16
I'm closing this issue, I think most of the stuff here has been addressed on master.

**Closed by rsdy** 2020-02-27 11:16 UTC
